" general settings
let mapleader = " "

set title
set path+=**
set nocompatible
set tabstop=4 softtabstop=4
set shiftwidth=4
set expandtab
set smartindent
set showcmd
set showmode
syntax on
set number
set relativenumber
set wrap
set ignorecase
set smartcase
set incsearch
set scrolloff=8
set encoding=utf-8
set nohlsearch
set mouse=a
set clipboard+=unnamedplus
set complete+=kspell
set completeopt=menuone,longest
set splitbelow splitright
set laststatus=2

"remap split navigation to just CTRL + hjkl
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

"adjust split sizes easier
noremap <silent> <C-Left> :vertical resize +3<CR>
noremap <silent> <C-Right> :vertical resize -3<CR>
noremap <silent> <C-Up> :resize -3<CR>
noremap <silent> <C-Down> :resize +3<CR>

"open terminal inside vim
map <leader>tt :vnew term://bash<CR>

"change split windows from vertical to horizontal or vice versa
map <leader>th <C-w>t<C-w>H
map <leader>tk <C-w>t<C-w>K

"remap ESC to various keys
:imap Capslock <Esc>
:imap jk <Esc>
:imap kj <Esc>

"open vifm
nnoremap <leader>vs :Vsplit Vifm<CR>

"remove trailing whitespace on save
autocmd BufWritePre * %s/\s\+$//e

" automatically close brackets, parethesis, double quotes, and single quotes
inoremap " ""<left>
inoremap ' ''<left>
inoremap ( ()<left>
inoremap [ []<left>
inoremap { {}<left>
inoremap {; {};<left><left>
inoremap /* /**/<left><left>

