#!/bin/bash

BATTERY=0
BATTERY_INFO=$(acpi -b | grep "Battery ${BATTERY}")
BATTERY_STATE=$(echo "${BATTERY_INFO}" | grep -wo "Full\|Charging\|Discharging\|Unknown")
BATTERY_POWER=$(echo "${BATTERY_INFO}" | grep -o '[0-9]\+%' | tr -d '%')
BATTERY_TIME=$(echo "${BATTERY_INFO}" | grep -o '[0-9]\+:[0-9]\+')
URGENT_VALUE=20

function return_message(){

    if [[ "${BATTERY_POWER}" = "100" ]]; then
        message="  100% ${BATTERY_TIME}"
    elif [ "${BATTERY_POWER}" -lt "100" ] && [ "${BATTERY_POWER}" -ge "80" ]; then
		message=" ${BATTERY_POWER}%  ${BATTERY_TIME}"
	elif [ "${BATTERY_POWER}" -lt "80" ] && [ "${BATTERY_POWER}" -ge "60" ]; then
	  	message=" ${BATTERY_POWER}%  ${BATTERY_TIME}"
	elif [ "${BATTERY_POWER}" -lt "60" ] && [ "${BATTERY_POWER}" -ge "40" ]; then
		message=" ${BATTERY_POWER}%  ${BATTERY_TIME}"
	elif [ "${BATTERY_POWER}" -lt "40" ] && [ "${BATTERY_POWER}" -ge "20" ]; then
		message=" ${BATTERY_POWER}%  ${BATTERY_TIME}"
	elif [ "${BATTERY_POWER}" -lt "20" ]; then
		message=" ${BATTERY_POWER}%  ${BATTERY_TIME}"
	fi
}


if [[ "${BATTERY_STATE}" = "Charging" || "${BATTERY_STATE}" = "Full" ]]; then
	return_message
	echo "$message ⚡"
fi


if [[ "${BATTERY_STATE}" = "Discharging" ]]; then
	return_message
	echo "$message"
fi

if [[ "${BATTERY_POWER}" -le "${URGENT_VALUE}"  &&  "${BATTERY_STATE}" = "Discharging" ]]; then
    notify-send "⚠️ Battery Low!! Please charge" -h string:x-canoncial-private-synchronous:anything
    exit 33
fi


if [ "${BATTERY_STATE}" = "Unknown" ]; then
    notify-send "☢️ Battery Not Charging!!!! Warning" 
	echo "$BATTERY_POWER % NOT CHARGING"	
	exit 33
fi
