#!/bin/sh
sink=0
volume=$(pactl list sinks | perl -slne '
    if (/^Sink #(\d+)$/) {
        $cur_sink = $1;
    } elsif (/^\s+Volume:.*? (\d+)% / && $sink eq $cur_sink) {
        print $1;
    }
' -- -sink="$sink")
volume=$((volume + 5))
volume=$((volume > 150 ? 150 : volume))
pactl set-sink-volume "$sink" "$volume%"
pkill -SIGRTMIN+11 i3blocks
notify-send  "🎧 ${volume} / 150%" -h string:x-canonical-private-synchronous:anything
